### PR TITLE
Add debug_test to CI regression

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
The (partial) debug_test is now passing, so it can be added back to the CI regression.

### CODE REVIEW

**Review by LeeHoff — APPROVED** [review]
Looks fine.

**Comment by MikeOpenHWGroup** [comment]
Thanks @LeeHoff.  The "GitHub work culture" is such that the creator of the pull-request (me, in this case) should not do the merge.  Merges are executed by one of the Committers working on the project (such as yourself).  Given that you are a Committer for this project _and_ have approved it, it makes sense for you to do the merging.

**Comment by LeeHoff** [comment]
It looks like I can close this PR, but I don't think I have the privilege to commit it.

**Comment by MikeOpenHWGroup** [comment]
Thanks @LeeHoff.  Although it is a deviation of the Eclipse workflow I will merge this in based on your approval (and will also start working on your Committer election).

**Pull request merged**
