### PR TITLE
code coverage: add CI jobs (generated tests & report)

### PR DESCRIPTION
**Pull request by AyoubJalali**
Signed-off-by: Ayoub Jalali <ayoub.jalali@external.thalesgroup.com>

### CODE REVIEW

**Comment by AyoubJalali** [comment]
Hello @JeanRochCoulon, could you look at these PR related to Continuous integration  for the Generated tests using RISCV-DV.

**Comment by JeanRochCoulon** [comment]
Great @AyoubJalali,
Two questions:
- I am quite surprised to see this job in CVA6 repository, why did you no timplemnt it in core-v-verif ?
- The 3 coverage jobs are quite the same, better would be to merge them into one single job thanks to the "matrix" command.

**Comment by JeanRochCoulon** [comment]
Two other comments:
- You do not need to source VIVADO
- The Artifact expiration for the final report is set to 1 week, maybe too short ?!?

**Comment by yanicasa** [comment]
Thanks @AyoubJalali, my comments:

- Can you move pub_generated_tests job to second stage and code_coverage-report to third stage to preserve pipeline length

- Can you remove "extends:-.template_job_always_manual" because "rules:-when:manual" overwrites it. As alternative option, you could add an "extend" that is really always manual.

- Artifacts are not properly handled and it won't work in CVA6 scope. In this pipeline, jobs artifacts should only be defined in a folder named "artifacts" at the root of the job's working directory. You have an example of management with the jobs pub_fpga-build and then pub_fpga-boot.

- For the dashboard layout, can you move DASHBOARD_* variables into the matrix section:
```
parallel:
    matrix:
        - list_num: 0
          DASHBOARD_JOB_TITLE: "Generated tests list 0"
          DASHBOARD_JOB_DESCRIPTION: "Generate Random tests using the RISCV-DV"
          DASHBOARD_SORT_INDEX: 11
          DASHBOARD_JOB_CATEGORY: "Code Coverage "
        - list_num: 1
          DASHBOARD_JOB_TITLE: "Generated tests list 1"
          DASHBOARD_JOB_DESCRIPTION: "Generate Random tests using the RISCV-DV"
          DASHBOARD_SORT_INDEX: 11
          DASHBOARD_JOB_CATEGORY: "Code Coverage"
        - list_num: 2
          DASHBOARD_JOB_TITLE: "Generated tests list 2"
          DASHBOARD_JOB_DESCRIPTION: "Generate Random tests using the RISCV-DV"
          DASHBOARD_SORT_INDEX: 11
          DASHBOARD_JOB_CATEGORY: "Code Coverage"
```

**Comment by AyoubJalali** [comment]
@yanicasa Thanks for your comment, really appreciated

**Comment by AyoubJalali** [comment]
One more thing, is it ok to just keep "rules:-when:manual"

**Comment by yanicasa** [comment]
> 

it's ok for me

**Comment by yanicasa** [comment]
You can move only DASHBOARD_JOB_TITLE to matrix as others DASHBOARD_* are not modified

**Comment by AyoubJalali** [comment]
@yanicasa, would you review the changes ? Thanks !!

**Review by ASintzoff — APPROVED** [review]
LGTM

Thanks a lot!

**Pull request merged**
