### PR TITLE
Base model containing Pulp instructions

### PR DESCRIPTION
**Pull request by eroom1966**
@MikeCovrado 
Hi Mike, in the process of adding the pulp instructions to the base model
I will be making a similar commit to the e40p/dev

### CODE REVIEW

**Review by MikeOpenHWGroup — APPROVED** [review]
Looks good @eroom1966, and passes a local CI regression on Xcelium.

As this is an E40X PR, I will ask @silabs-hfegran to review and merge.

**Comment by Silabs-ArjanB** [comment]
@eroom1966 How does this relate to the requested updates for 0.2.0 of the CV32E40X? I see 0.2.0 mentioned in the PR, but from the provided documentation I conclude that not all its features have been implemented (e.g. NMI target address, Zc implementation).

**Comment by eroom1966** [comment]
> @eroom1966 How does this relate to the requested updates for 0.2.0 of the CV32E40X? Are the requested 0.2.0 features fully implemented?

Not yet, this is still a work in progress

**Comment by silabs-hfegran** [comment]
@eroom1966 Is this duplicated by PR #1249 that was merged a while back?

**Pull request closed without merging**
