### PR TITLE
modify makefile to run 'sanity' test with vcs

### PR DESCRIPTION
**Pull request by davidchen6**

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @davidchen6, thanks for the pull-request.   Can you provide some additional detail?   What is the command line you are trying to use?

**Comment by davidchen6** [comment]
> Hi @davidchen6, thanks for the pull-request. Can you provide some additional detail? What is the command line you are trying to use?
cmd under cv32/sim/uvmt_cv32:   make SIMULATOR=vcs sanity

**Comment by davidchen6** [comment]
> Hi @davidchen6, thanks for the pull-request. Can you provide some additional detail? What is the command line you are trying to use?

The custom test directory has been moved to cv32/tests/program from cv32/tests/core and each custom test has its individual folder. So the makefile for custom test needs to  be adapted for these changes.

**Comment by MikeOpenHWGroup** [comment]
Hi @davidchen6, thanks for the clarification.  You are right about that.  As it turns out, @masgia has submitted pull-request #335, which was intended to solve a different issue, but he was kind enough to also resolve this issue.   I expect to get this merged in tomorrow (need another member of the team to review #335).

**Comment by davidchen6** [comment]
> Hi @davidchen6, thanks for the clarification. You are right about that. As it turns out, @masgia has submitted pull-request #335, which was intended to solve a different issue, but he was kind enough to also resolve this issue. I expect to get this merged in tomorrow (need another member of the team to review #335).

Hi Mike, got it .

**Pull request closed without merging**
