### PR TITLE
RISCV CVA6 32-bit CSR Access Verification PR-1

### PR DESCRIPTION
**Pull request by spidugu444**
Hi,

please find the PR for CVA6 32-bit CSR Access Verification.

Highlights:

    1. Added Yaml files for CVA6 32-bit CSRs, which has been categorized into supervisor mode read-write CSRs, Machine mode read-write CSRs and read-only CSRs.
    2. Added Test files for CVA6 32-bit CSRs, which has been categorized into supervisor mode read-write CSRs, Machine mode read-write CSRs, read-only CSRs and counter CSRs. each CSR has been verified on all privileged modes (Supervisor, Machine and User modes).
    3. Added CVA6 32-bit CSR access failing test cases.
please let me know if any changes are needed.

Thanks

### CODE REVIEW

**Review by MikeOpenHWGroup — APPROVED** [review]
This looks fine to me @spidugu444, thanks for this!  However, we cannot merge these files in until the failing CI test is passing.   I do not think the failure has anything to do with these changes, but we need to understand the root cause before merging.

**Comment by MikeOpenHWGroup** [comment]
Hi @ASintzoff, this is an example of a pull-request into `core-v-verif/cva6/dev` that is failing CI.  In this example the CI has two failures:
- One test out of 106 tests in the `riscv-test regression suite` (tests/isa/rv64ua/lrsc.S)
- An unknown failure of the `CSR regression suite`

Can you investigate?  Thanks.

**Comment by ASintzoff** [comment]
> Hi @ASintzoff, this is an example of a pull-request into `core-v-verif/cva6/dev` that is failing CI. In this example the CI has two failures:
> 
>     * One test out of 106 tests in the `riscv-test regression suite` (tests/isa/rv64ua/lrsc.S)

Until 2023-08-07, lrsc.S test can behave differently on Spike and on CVA6 (even both behaviours are RISC-V compliant). With PR #2103, their behaviours are now the same. 
Either we need to rebase all pending PRs or we consider they are OK if the only failing test is that one as most PRs have nothing related to Load-Reserved/Store-Conditional.
 
>     * An unknown failure of the `CSR regression suite`

Should to be fixed with commit a99981d

> Can you investigate? Thanks.

**Comment by ASintzoff** [comment]
Is there any reason to merge from master branch?

First, it will be better to rebase the PR on top of cva6/dev branch in order to get green CI.

**Comment by spidugu444** [comment]
Closing this PR as new [PR](https://github.com/openhwgroup/core-v-verif/pull/2139) has raised with all updated changes.

**Pull request closed without merging**
