### PR TITLE
cva6/docs/verif-approval: add file describing task approval process

### PR DESCRIPTION
**Pull request by ASintzoff**
As discussed during CVA6 verification meeting, the goal of this file is to record formal approval for the different verification tasks.

### CODE REVIEW

**Review by JeanRochCoulon — APPROVED** [review]

**Comment by JeanRochCoulon** [comment]
@AEzzejjari @AyoubJalali Can you approve the document ?

**Comment by AyoubJalali** [comment]
Hello @ASintzoff, thanks for creating this file I have some points to be disccus :

- We should have a place to mention the responsible for the task (for ISACOV is me, AXI is Alae for example).
- You talk about explaining the missing coverage, should just add a section for this in this file or implement it in different one.

**Comment by JeanRochCoulon** [comment]
This make me think we need to identify the specification, dvplan and rtl which has been verified (version, hash,...)

**Comment by JeanRochCoulon** [comment]
@ASintzoff   The merge is on your hands!

**Pull request merged**
