### PR TITLE
Add CSR pseudo-instructions to ISACOV

### PR DESCRIPTION
**Pull request by AyoubJalali**
This PR fix [CSR Pseudo-instruction issue](https://github.com/openhwgroup/core-v-verif/issues/2326)

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
As per my comment in #2326, there is no need for functional coverage of pseudo-instructions.

**Comment by AyoubJalali** [comment]
> As per my comment in #2326, there is no need for functional coverage of pseudo-instructions.

I'm not trying to add functional coverage for psudo-code, I'm trying to add the capability to ISACOV to know this CSR pesudo-code and not drive me an UNKNOWN instruction.

**Comment by silabs-hfegran** [comment]
Is there a way to have spike output the proper instruction names instead of the pseudo names? I think that would be cleaner than adding support for pseudo-instructions to isacov.

**Comment by AyoubJalali** [comment]
> Is there a way to have spike output the proper instruction names instead of the pseudo names? I think that would be cleaner than adding support for pseudo-instructions to isacov.

No idea to be honest, but I think after the spike tandem version, something changed in spike-dasm (I think we don't use spike-dasm in lib/ or something else)

**Comment by silabs-hfegran** [comment]
Completely untested, but I suspect it could be as easy as removing these four lines of code from `disasm/disasm.cc` in spike
```  
  add_insn(new disasm_insn_t("csrr", match_csrrs, mask_csrrs | mask_rs1, {&xrd, &csr}));
  add_insn(new disasm_insn_t("csrw", match_csrrw, mask_csrrw | mask_rd, {&csr, &xrs1}));
  add_insn(new disasm_insn_t("csrs", match_csrrs, mask_csrrs | mask_rd, {&csr, &xrs1}));
  add_insn(new disasm_insn_t("csrc", match_csrrc, mask_csrrc | mask_rd, {&csr, &xrs1}));
  ```

**Comment by AyoubJalali** [comment]
As waiting for the decoder, I'll close this PR

**Pull request closed without merging**
