### PR TITLE
[TANDEM] Debug events injection

### PR DESCRIPTION
**Pull request by MarioOpenHWGroup**
* rvfi_dbg: make the field compliant with cv32e40s
* Add debug injection on riscv-isa-sim

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@zchamski    The bump of this PR works on cva6 side https://github.com/openhwgroup/cva6/pull/2263 
The merge is pending to approval

**Review by zchamski — APPROVED** [review]
LGTM! The generalized masking feature is very welcome as it simplifies both Spike code and parameterization process.

**Review by JeanRochCoulon — APPROVED** [review]
Thank you @zchamski for your review.  Better is to approve by clicking on the dedicated button for the next times (otherwise, I need to approve myself before merging, no problem except that I did not review carefully the code).

**Comment by JeanRochCoulon** [comment]
It is merged, @MarioOpenHWGroup you can update your CVA6 PR now.

**Comment by MarioOpenHWGroup** [comment]
Sure!

**Pull request merged**
