### PR TITLE
CVA6: Infrastructure improvements

### PR DESCRIPTION
**Pull request by MarioOpenHWGroup**
This reverts the revert to fix the CI.

It has the content of the #1888 #1846.

### CODE REVIEW

**Comment by MarioOpenHWGroup** [comment]
> Hi @MarioOpenHWGroup, what is the status of this PR? It is marked "Draft" which means it will probably not receive a review. Also the other content you mention in #1888 and #1846 are already merged.

Draft is because this changes were breaking the Thales CI, so some fixes are required. I do not know why is failing and I do not have the logs in order to solve it.

**Comment by cathales** [comment]
Hello,

Here is the Dashboard status for this PR:

https://riscv-ci.pages.thales-invia.fr/dashboard/dashboard_core-v-verif_1893.html

The last run is all green. Maybe the red flags in your previous PR were CI environment issues and not related to your code?

To be sure that there are no post-merge issues, could you rebase your branch on `cva6/dev`, please? If the CI passes, I vote for merging this PR.

**Comment by MarioOpenHWGroup** [comment]
> Hello,
> 
> Here is the Dashboard status for this PR:
> 
> https://riscv-ci.pages.thales-invia.fr/dashboard/dashboard_core-v-verif_1893.html
> 
> The last run is all green. Maybe the red flags in your previous PR were CI environment issues and not related to your code?
> 
> To be sure that there are no post-merge issues, could you rebase your branch on `cva6/dev`, please? If the CI passes, I vote for merging this PR.

Rebased :+1:

**Comment by JeanRochCoulon** [comment]
Thanks for this PR !

**Pull request merged**
