### PR TITLE
Load store rs1 eq 0

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
Hi @strichmo, it turns out that Greg is on vacation so I took the load/store coverage holes.  Please do not merge this yet as I am running a regression to see if it actually _does_fill the holes.  I may need to push in a few updates in the morning.

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @strichmo, I've hit 100 ISA Fcov (ignoring the cross-coverage) with this PR.  Please review and merge this in at your earliest convenience.

**Comment by MikeOpenHWGroup** [comment]
Also pushed in an update to cover accesses to CSR_LPEND1 (actually, cover read/write to all User Custom CSRs).

**Review by strichmo — APPROVED** [review]

**Comment by strichmo** [comment]
Thanks...this just may well get us to 100 across the board!

**Comment by GTumbush** [comment]
These were covered by pull request https://github.com/openhwgroup/core-v-verif/pull/380 merged on Nov 17.  Did the test not get included for coverage?

**Comment by MikeOpenHWGroup** [comment]
> These were covered by pull request #380 merged on Nov 17. Did the test not get included for coverage?

We got everything except `lui rs1 imm` where imm == 0.   I've added that to a fork that I'll be PR'ing in today.

**Pull request merged**
