### PR TITLE
Fixed rvvi memory backdoor for misaligned accesses to volatile memory

### PR DESCRIPTION
**Pull request by silabs-hfegran**
This commit addresses a regression error that is observed with the fence.i tests, where the ISS memory backdoor corrupts ISS memory due to erroneous handling of misaligned data addresses.

### CODE REVIEW

**Comment by silabs-robin** [comment]
This looks right to me.
Previously, the memory would get updated for address `mem_addr >> 2`, but that would update to a word-aligned address regardless of whether the access was actually word-aligned or not.

ps. I am still, in general, confused about our policy about the "volatile" memory regions, but regardless of that I think this PR correctly fixes a real problem.

**Comment by MikeOpenHWGroup** [comment]
Hi @silabs-hfegran, this PR looks good but git seems to think there is a conflict.  Can you have a look?

**Comment by silabs-hfegran** [comment]
> Hi @silabs-hfegran, this PR looks good but git seems to think there is a conflict. Can you have a look?

Hi @MikeOpenHWGroup , 
the merge conflict should be resolved now

**Review by MikeOpenHWGroup — APPROVED** [review]
Thanks for cleaning up the conflict @silabs-hfegran.  My local tests pass so this is good-to-go.

**Pull request merged**
