### PR TITLE
Fix to match RTL signals

### PR DESCRIPTION
**Pull request by silabs-hfegran**
Implements #1111 and #1102 for CV32E40X onto CV32E40S

### CODE REVIEW

**Comment by silabs-robin** [comment]
@silabs-hfegran I think I already did this as part of the merge from 40x->40s.
But it could still be nice to get this PR in as a double check that I got that merging right.

**Comment by Silabs-ArjanB** [comment]
@silabs-hfegran Agreed with Robin, it is weird that this PR is needed if files have already been merged from 40X to 40S

**Review by Silabs-ArjanB — APPROVED** [review]
Looks okay, but it is weird that this is a separate PR.

**Comment by silabs-hfegran** [comment]
> Looks okay, but it is weird that this is a separate PR.

Sorry about this - simulation was broken for 40s devs, so I expedited this change to enable devs to be able to run simulations on 40s based on latest hash.

**Pull request merged**
