### PR TITLE
Gitlab-ci: add synthesis partial log, specify oder, workflow bypass, fix error code simu

### PR DESCRIPTION
**Pull request by yanicasa**
Related do gitlab-ci flow:

- synthesis report add partial log
- Add a way to specify order of jobs and metrics in dashboard
- Do not return error code in case of test fail.
- Add way to disable workflow policy

### CODE REVIEW

**Review by Gchauvon — APPROVED** [review]
LGTM

**Comment by yanicasa** [comment]
For me it's clean ready to merge

pipeline https://riscv-ci.pages.thales-invia.fr/dashboard/dashboard_core-v-verif.html
=> 2 test fails but not related to this PR

**Comment by yanicasa** [comment]
https://github.com/openhwgroup/core-v-verif/issues/1296

**Review by zchamski — COMMENTED** [review]
LGTM

Inquiring mind wants to know: the quoting change comes from applying Black?

**Pull request merged**
