### PR TITLE
Fix Issue #1456

### PR DESCRIPTION
**Pull request by AyoubJalali**
Signed-off-by: Ayoub Jalali <ayoub.jalali@external.thalesgroup.com>

### CODE REVIEW

**Review by silabs-robin — APPROVED** [review]
Approving based on: Matches expectations from the discussion in the referenced issue.

**Comment by MikeOpenHWGroup** [comment]
Thanks for this @AyoubJalali (and thanks for the review/approval @silabs-robin).   This LGTM but before merging I would like to understand why @silabs-hfegran added the `cva6` label to this PR.  It _is_ true that this PR goes to the `cva6/dev` branch, but it is my understanding that this PR, once merged, would eventually be merged to affect all dev branches on core-v-verif.

Is there anything special about this PR that makes it a "cva6-only" update?

**Comment by AyoubJalali** [comment]
Hello @MikeOpenHWGroup 
No, it just a correction in a cover point definition in the coverage model, So there isn't anything special to make it only related to cva6.

**Comment by silabs-robin** [comment]
> Is there anything special about this PR that makes it a "cva6-only" update?

There should not be anything cva6-only here.

My guess is that the label was added because it makes it much quicker to read [the list of open PRs](https://github.com/openhwgroup/core-v-verif/pulls).
(It would e.g. make it easier for him to scan for PRs that he should merge.)

**Comment by MikeOpenHWGroup** [comment]
Thanks for the confirmation.  Merging...

**Pull request merged**
