### PR TITLE
Add gcc option to compile cvxif tests with cv32a60x target

### PR DESCRIPTION
**Pull request by AyoubJalali**

### CODE REVIEW

**Comment by zchamski** [comment]
@AyoubJalali , the need for `-lgcc` looks more like a side effect of the new test termination support in `cva6/tests/custom/common/syscalls.c` introduced by myself (@zchamski) in PR https://github.com/openhwgroup/core-v-verif/pull/1689.  I will look at the code and see if I can remove this dependency on GCC runtime.

**Comment by AyoubJalali** [comment]
I think that was before adding the new test termination

**Comment by MikeOpenHWGroup** [comment]
> A possible way to proceed is to create a simplified version of syscalls.c that will just provide an exit() function reduced to the bare minimum.

This is a BIG topic and beyond the scope of a GitHub issue.  If the CVA6 simulation environment needs this, then it should be discussed in @JeanRochCoulon's weekly CV32A6 v5 verification meeting.

**Review by zchamski — APPROVED** [review]
LGTM.  The `libgcc` runtime library of GCC provides the necessary emulation of 64b operations when compiling the `syscalls.c` BSP file for a 32b target (see the main conversation about the PR).

Please rebase on latest `cva6/dev` branch and let's see the subsequent CI status.

**Comment by AyoubJalali** [comment]
I'm gonna close this PR, I'm working on another one that gonna include the changes of this one.

**Pull request closed without merging**
