### PR TITLE
Remove rand weights of dist

### PR DESCRIPTION
**Pull request by dawidzim**
Hey!
I remove rand weights of dist
Signed-off-by: Dawid Zimonczyk <dawidz@aldec.com.pl>

### CODE REVIEW

**Review by MikeOpenHWGroup — CHANGES_REQUESTED** [review]
I am not sure this is a god idea @dawidzim.  We have spent considerable time tuning corev-dv (an extension of Google's riscv-dv) to reliably achieve high functional and code coverage in regression.

I will ask @strichmo, our resident expert on riscv-dv, to review this pull-request.

**Review by strichmo — CHANGES_REQUESTED** [review]
I'm not sure why the rand qualifier on the weights are removed.  Is it an issue with the simulator or an issue with code-style/functionality?

**Comment by danielmlynek** [comment]
It is both coding style and simulator issue.
It is not good coding style in my opinion. I rather doubt if you want to have random weights - it would be hard to analyze what would be the final distibution. 
Weights are rather parameters which should be known before randomization.

**Comment by MikeOpenHWGroup** [comment]
> It is not good coding style in my opinion. I rather doubt if you want to have random weights

I cannot comment about this specific instance, but I have often used random weights in past projects.  It can be a powerful method of creating unforeseen stimulus patterns or device configurations.

**Comment by danielmlynek** [comment]
My comment is based on my opinion from simulator point of view. My point is that having random weights cause that in fact the distribution is not definded. Each randomization is done with different weights. If I would like to have random weights I would randomize them (separately) once per some simulation period as a configuration.
I've also noticed that your weights are constrainted to constant values by some soft constraints. I thought that you rather want to have them const. You need to define on them conflicting constraint to make them random.
If you are saying that having random weight is important for verification process - then thank you for your feedback - we will take it into account.

**Comment by MikeOpenHWGroup** [comment]
Thanks for the additional information @dawidzim.  When it comes to such matters, there is the question about what the language simulator should support and how the coder should use the language.

Both randomization of weights and soft constraints are legal as so far as the SV LRM is concerned, so I would argue that all SV simulators must support both.

As for coding styel, in this instance it makes sense to randomize distributions as it means we will get a different distribution of MIE and MSTATUS_MIE actions for each simulation run.   Without that the base class (riscv_load_store_rand_instr_stream) will generate a fixed ratio, regardless of the number of sims and this has made closing coverage difficult.

Whether or not soft constraints should be used is almost a matter of religion and I avoid discussing such topics.  :wink:

So I agree with @strichmo, that we should leave the code as-is.   However, if the code as written is not supported by Riviera-PRO, please do update this pull request with a macro to avoid such constructs at compile-time.   I believe the macro \_VCP has been used in the past for this.

**Comment by danielmlynek** [comment]
>I believe the macro _VCP has been used in the past for this.

We will uptade PR with ifdefs

>As for coding styel, in this instance it .....

That is exactly what I was writing about - different dist weights for each simulation run or at least for some number of randomizations is great idea. But rerandomizing dist weights in each randomization is not so good idea.

**Review by MikeOpenHWGroup — APPROVED** [review]
Thanks for this @dawidzim.   This runs clean under DSIM.

**Comment by MikeOpenHWGroup** [comment]
Hi @strichmo, I am happy with this PR as it stands now.  Since you've requested changes in your previous review, GitHub needs you to re-review before it can be merged in.   Thanks.

**Review by strichmo — APPROVED** [review]

**Pull request merged**
