### PR TITLE
Help needed with ECA check. 

### PR DESCRIPTION
**Pull request by ShashankVM**
Test only

Signed-off-by: Shashank V M <shashankmathew8@gmail.com>

### CODE REVIEW

**Comment by ShashankVM** [comment]
Need help. Unable to sign off. I have added the required footer and signed the commit. I have also signed the Eclipse Contributor Agreement @eclipsewebmaster

**Comment by ShashankVM** [comment]
Do not merge

**Comment by MikeOpenHWGroup** [comment]
Hi @ShashankVM.  I see you made several attempts but were not able to get the ECA check to work.  I was able to use my admin priviledges to merge in the update, so at least we know that that you are able to submit code.   Did you use the `-s` switch for the `git commit` command?   This is how your ECA creditentials are forwarded to sign-off your pull-request.

**Comment by ShashankVM** [comment]
Hi @MikeOpenHWGroup. I used the GUI Gitkraken, but I signed the commit. You can see the green 'verified' tag on my pull-request along with the commit signature here.

**Pull request merged**
