### PR TITLE
Cv32e40x/dev

### PR DESCRIPTION
**Pull request by eroom1966**
Apologies for previous PR error
This should now be resolved with these changes

### CODE REVIEW

**Comment by strichmo** [comment]
@eroom1966 Should I expect that the deferint+LoadBusFaultNMI functionality for entering the NMI is implemented in this model release?

**Comment by eroom1966** [comment]
Hi Steve, 
No it is not, this was simply a move of the signals from the rvvi.bus to rvvi.io
I should have the deferint setup and working first thing Monday

Would you be able to create a test which I could use to ensure this matches the expectation ?

thx
Lee

**Comment by strichmo** [comment]
Thanks for clarifying.  I'll get this merged, then get my own PR merged that will provide deferint + NMI signaling in a directed test.

**Comment by strichmo** [comment]
Passes regression.  Merging this now and will follow up with a directed test PR to enable @eroom1966 to test NMI feature.

**Pull request merged**
