### PR TITLE
cv32e40s verification environment

### PR DESCRIPTION
**Pull request by silabs-hfegran**
Port of the cv32e40x verification environment to cv32e40s

This is based of latest cv32e40x/dev but should probably be branched out to its own branch.

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
> This is based of latest cv32e40x/dev but should probably be branched out to its own branch.

Agree that this should be on its own branch.  Let's create a `cv32e40s/dev` branch and push this PR to there.

**Review by strichmo — CHANGES_REQUESTED** [review]
We would like to remove the testplans referencing the E40X (i.e. the Excel files) in cv32e40s/doc/VerifPlans in this initial commit.  We can then add them in later (with proper names).

**Comment by silabs-hfegran** [comment]
> We would like to remove the testplans referencing the E40X (i.e. the Excel files) in cv32e40s/doc/VerifPlans in this initial commit. We can then add them in later (with proper names).

Ok! thanks

**Review by MikeOpenHWGroup — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
Hi @strichmo, I see that @silabs-hfegran cleaned up the old SV plan spreadsheets, so I will approve and merge this so that the E40S can move forward.

Thanks for your efforts to get this in Henrik!

**Pull request merged**
