### PR TITLE
Merge cva6/dev up onto master

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
Hi @JeanRochCoulon and @ASintzoff.  As we discussed last week, we should be striving to keep the master branch up-to-date with cva6/dev.  This is important for several reasons:
- The CV32E40X team is interested in the most recent updates to the CV-XIF Agent.
- Members of the open-source community who are not yet members of OpenHW will look at the master branch first.
- The longer we wait to do this, the more painful it becomes!

@silabs-hfegran, I requersted your review, not because I think you will want to look at the CVA6 specific code, but just to be aware this is happening as it will naturally impact your mergings of the e40x and e40s dev and release branches.

### CODE REVIEW

**Comment by silabs-hfegran** [comment]
Thanks for the heads-up, @MikeOpenHWGroup, this looks good to me (and does not break my local regressions)

**Comment by ASintzoff** [comment]
> Hi @JeanRochCoulon and @ASintzoff. As we discussed last week, we should be striving to keep the master branch up-to-date with cva6/dev.

I would prefer if the latest available cva6/dev commit (153b1df5ae) will be merged into master as it fixes some problems with vcs-uvm DV_SIMULATOR.
Note: the PR does not break verilator regressions.

**Comment by MikeOpenHWGroup** [comment]
Hi @ASintzoff 
> I would prefer if the latest available cva6/dev commit ([153b1df](https://github.com/openhwgroup/core-v-verif/commit/153b1df5ae4742f5019787ad65b638bb04fa306a)) will be merged into master as it fixes some problems with vcs-uvm DV_SIMULATOR.

I can confirm that this pull-request automatically picked up the cva6/dev commit 153b1df.

**Comment by MikeOpenHWGroup** [comment]
Hi @JeanRochCoulon, both @ASintzoff and @silabs-hfegran has "blessed" this PR, but it needs an approval from an Eclipse Committer.  That could be me, @silabs-hfegran or you.  I think it makes the most sense that the approval comes from you since you are the OpenHW Committer who is also the CVA6 verification leader.

**Comment by ASintzoff** [comment]
> Hi @ASintzoff
> 
> > I would prefer if the latest available cva6/dev commit ([153b1df](https://github.com/openhwgroup/core-v-verif/commit/153b1df5ae4742f5019787ad65b638bb04fa306a)) will be merged into master as it fixes some problems with vcs-uvm DV_SIMULATOR.
> 
> I can confirm that this pull-request automatically picked up the cva6/dev commit [153b1df](https://github.com/openhwgroup/core-v-verif/commit/153b1df5ae4742f5019787ad65b638bb04fa306a).

I misunderstood the GitHub workflow. So, LGTM.

**Review by JeanRochCoulon — APPROVED** [review]

**Comment by JeanRochCoulon** [comment]
@MikeOpenHWGroup It is approved !

**Pull request merged**
