### PR TITLE
Restore Questa (vsim)

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
Makefile for Questa (vsim) was out-of-date.  Added the `-64` compile time switch.

Signed-off-by: Mike Thompson <mike@openhwgroup.org>

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@Gchauvon The HWconfig CI jobs are failed, could you have a look please ?

**Comment by MikeOpenHWGroup** [comment]
> @Gchauvon The HWconfig CI jobs are failed, could you have a look please. Maybe the fix you proposed has been merged in cva6/dev branch and not yet with master branch ?

Would that issue be related to this?   Is cva6 using `mk/uvmt/vsim.mk`?

**Comment by Gchauvon** [comment]
The issue with HW_CONFIG is not related to this PR. It has been resolved in cva6/dev branche. 
I have no issue with this PR but i cannot review it because I don't have questa tools.

**Comment by MikeOpenHWGroup** [comment]
Thanks @Gchauvon.  Given that this is a blocker for a Contributor working with Questa, I will merge it in.

**Review by JeanRochCoulon — APPROVED** [review]

**Pull request merged**
