### PR TITLE
disable scheduled regression on the e40p

### PR DESCRIPTION
**Pull request by strichmo**
using workflow_dispatch in schedule to convert this action to manual-start only

Signed-off-by: Steve Richmond <Steve.Richmond@silabs.com>

### CODE REVIEW

**Review by GTumbush — COMMENTED** [review]
I thought we were going to leave regressions running since we still have 4 ISS licenses.

**Comment by strichmo** [comment]
I would like to see the results of Mike's manual run on Friday with regards to length of time of regression before re-enabling this.  We can decide on a schedule after that.

**Review by MikeOpenHWGroup — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
@GTumbush, are you good with this change?  If so, please hit the approve button.   Thanks.

**Review by GTumbush — APPROVED** [review]
Approved

**Pull request merged**
