### PR TITLE
Remove strong operator in cvxif SVA to match VCS 2023 version

### PR DESCRIPTION
**Pull request by AyoubJalali**
This MR change a cvxif assertion to compile it in the latest version of VCS 2023, the assertion remain as before in term of logic

### CODE REVIEW

**Review by MikeOpenHWGroup — CHANGES_REQUESTED** [review]
Would it be possible to add a one or two line comment to each property and sequence to explain what it does?  Reverse engineering these will be very time-consuming otherwise.

**Comment by AyoubJalali** [comment]
> Would it be possible to add a one or two line comment to each property and sequence to explain what it does? Reverse engineering these will be very time-consuming otherwise.

That's would be useful, on it !!

**Comment by Gchauvon** [comment]
This PR is quite critical as it is mandatory to open waveform with VCS/VERDI since parametrization on CVA6.

@MikeOpenHWGroup can you open an issue for adding comments on property and sequence ? So we can merge this ASAP.

**Comment by AyoubJalali** [comment]
> This PR is quite critical as it is mandatory to open waveform with VCS/VERDI since parametrization on CVA6.

The commit requested by Mike is ready to be pushed in github, only a review is needed

**Review by MikeOpenHWGroup — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
Thanks @AyoubJalali!

**Pull request merged**
