### PR TITLE
fix issue #1225 ;

### PR DESCRIPTION
**Pull request by leemango1998**
Add `$CUSTOM` path for vsim; 
syntax error: Add a space before new line symbol at make target `vsim-run`.

### CODE REVIEW

**Review by MikeOpenHWGroup — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
Thanks very much for this PR @leemango1998!  Before I can merge it in, you will need to sign the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php).  This is explained in our [CONTRIBUTING](https://github.com/openhwgroup/core-v-verif/blob/master/CONTRIBUTING.md) document at the top of the repository.

Do not worry, it is very easy.  Please let me know if you have any questions.

**Comment by leemango1998** [comment]
OK. I have signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) at eclipse.org just now.

**Comment by MikeOpenHWGroup** [comment]
Thanks @leemango1998.  What email address did you use for the ECA?  This PR was signed off with "319048894@****.com".  In order for the ECA check to work, the user email for the PR and the ECA must match.

**Comment by leemango1998** [comment]
I used the same email address. Both are 319048894@qq.com.

**Comment by MikeOpenHWGroup** [comment]
Ha!  Yes, you did.  I had to login to Eclipse and "revalidate" the PR.  It is all good now.  Thank you very much for your contribution and for following our validaton process.  Both are very much appreciated.

**Pull request merged**
