### PR TITLE
Overrides for marchid

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
Hi @strichmo, I'm picking on you to review this one since it adds a `cv32e40p.ic` config file for the Imperas RM and exports a shell variable to point to it.   Its my understanding you are considering something similar, so you can either suggest a different/better way to do this, or add your RM config updates to `cv32e40p.ic`.

Signed-off-by: Mike Thompson <mike@openhwgroup.org>

### CODE REVIEW

**Review by strichmo — CHANGES_REQUESTED** [review]
I have a more general commit incoming that should address the IC configuration issue in this PR in a very general way.  Unfortunately there is a large Internet outage in Austin currently and my hotspot is not holding a VPN connection so I can't finish up my PR.

**Comment by MikeOpenHWGroup** [comment]
OK, should I kill this PR?

**Comment by strichmo** [comment]
I believe so.  I filed the PR with the build config methodology implemented.  https://github.com/openhwgroup/core-v-verif/pull/231

**Comment by MikeOpenHWGroup** [comment]
Made redundant by #231.

**Pull request closed without merging**
