### PR TITLE
Updated reference to register file in step and compare module.

### PR DESCRIPTION
**Pull request by silabs-oysteink**
In RTL the register file has been moved from ID stage to toplevel.
Upated hash to point to the relevant RTL commit.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

### CODE REVIEW

**Review by MikeOpenHWGroup — COMMENTED** [review]
Hi @silabs-oysteink.  Thanks for taking the time to update the verification environment to track a change in the RTL.  Much appreciated.

This PR is fine on its own, but there _is_ an issue with the 40x RTL, see [cv32e40x #39](https://github.com/openhwgroup/cv32e40x/issues/39).  This issue is sure to generate a bun-fight as it only seems to affect DSIM, but in the meantime I am requesting that we wait until that issue is resolved before merging in this PR.

**Comment by MikeOpenHWGroup** [comment]
After the latest update to the RTL (see [cv32e40x #39](https://github.com/openhwgroup/cv32e40x/issues/39)), this PR runs clean.

@silabs-oysteink can you push in an update on this PR to line 18 of `cv32e40x/sim/Common.mk` to point to the hash of the 40x RTL with your fix?
```
CV_CORE_HASH   ?= 1f4389e 
```

**Review by strichmo — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
The cv32e40x at `f85707e` does not compile with either DSIM or XRUN.   I'm stuck in meetings for the next couple of hours and will investigate later today.

**Comment by strichmo** [comment]
Closing this pull request as 595 supersedes by incorporating the same probe fix and advancing the RTL pointer further in time.

**Pull request closed without merging**
