### PR TITLE
MMU test plan for SV32 address translation scheme

### PR DESCRIPTION
**Pull request by Abdulwadoodd**
Hi All,

This PR adds the Architecture test plan of the Virtual Memory - SV32 address translation scheme - for the verification of MMU of the RISC-V CV32A6 v5.0.0. 

Let me know if any changes are required.

Thanks,

### CODE REVIEW

**Comment by ASintzoff** [comment]
Could you update VPtool in order to get YAML files instead of Pickle (.pck) ones? If you need support on this topic, @zchamski can help you.
In addition, could you remove `locked_ip.pick` file from the commit?

**Comment by Abdulwadoodd** [comment]
@ASintzoff I have updated the commit by removing `locked_ip.pick`.

@zchamski Please point me out how can I modify the VP tool to generate YAML file/s. Thanks,

**Comment by Abdulwadoodd** [comment]
Thanks, @zchamski !
@ASintzoff PR is updated as per the requirement.

**Comment by JeanRochCoulon** [comment]
Hello @Abdulwadoodd   Happy to have time to review your dvplan !   Sorry for the delay
A quick question before jumping deeply in dvplan: chapter 5.3.2, 5.3.1 and 5.1.11 are referenced in your dvplan but the 20211203 version spec corresponds to the standard Extension for NAPOT Translation Continuity and it does not get subchapters. 
Can you commit the specification you are verifying in you dvplan directory?   That is the recommendation we give to all verificator contributors.
The sv32 is specified in chapter 4.3, I do not see dvplan features covered by dvplan, is it normal?

**Comment by Abdulwadoodd** [comment]
> That is the recommendation we give to all verificator contributors.
 
Sorry, I overlooked the option to add a URL of the specification that came with configuring the VP tool to get YAML instead of .pick files. I'll add url reference to the updated spec in dvplan with the additional commit, shortly.

> The sv32 is specified in chapter 4.3, I do not see dvplan features covered by dvplan, is it normal?

Please refer to the [latest spec](https://github.com/riscv/riscv-isa-manual/releases/download/riscv-isa-release-1239329-2023-05-23/riscv-privileged.pdf) from GitHub that has updated index which is consistent with the references in the test plan. Thanks,

**Comment by fatimasaleem** [comment]
Hi @Abdulwadoodd, in the last meeting we decided that it would be good to mention the test cases for which we will need to add functional cover points in the test plan. Can you update the testplan with the functional coverage information as well? Thank you.

**Comment by MikeOpenHWGroup** [comment]
Hi @Abdulwadoodd, @fatimasaleem, @zchamski, @JeanRochCoulon and @ASintzoff, good comments from everyone.  Question: should we merge the current DV plan as-is and then provide feedback, or should we provide feedback on this PR?  Maybe it would be a good idea to merge this in now and then update it later.

**Comment by Abdulwadoodd** [comment]
Hi @MikeOpenHWGroup, thanks for the feedback.

> Maybe it would be a good idea to merge this in now

I second. DV plan is good to go and I'm happy to make suggested changes later - in case that comes up. 

cc: @fatimasaleem

**Review by MikeOpenHWGroup — APPROVED** [review]
Approving based on our discussions at the 2023-08-10 CVA6 verification weekly meeting.  The conclusion was to merge this DVplan as it is now and update later after reviews.  Thanks @Abdulwadoodd!

**Pull request merged**
