### PR TITLE
Rename Mem_init.txt to expected name for vcs_core and vcs_gate target

### PR DESCRIPTION
**Pull request by Gchauvon**
Just a small fix : Mem_init.txt has been renamed to $(TESTNAME).txt in PR #1108. 
I have updated vcs_core and vcs_gate target so it would work with this PR.

### CODE REVIEW

**Review by JeanRochCoulon — COMMENTED** [review]
Hello Guillaume, just a little question. Why elf-bin option is added when making vcs_core_run ?

**Comment by Gchauvon** [comment]
`elf-bin` option is added because the variable `TESTNAME` takes it as its input. Otherwise the value of `TESTNAME ` is empty and Mem_init.txt can not be created.

**Review by JeanRochCoulon — APPROVED** [review]
Thanks for the explanations. It is ok for me !

**Comment by JeanRochCoulon** [comment]
@MikeOpenHWGroup As this PR corresponds to a Fix, I took the liberty of merging it.

**Pull request merged**
