### PR TITLE
Two toolchains: needs GLIBC_2.27

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
Please do not merge this PR at this time.

This pull-request is a set of updates that attempt to run the `cv32_interrupt_regression` using the COREV toolchain.

@aimeepsutton, with this pull-request a regression using the COREV toolchain compiles, but none of the test-programs successfully compile due to a missing library:
```
/opt/corev/bin/../lib/gcc/riscv32-corev-elf/11.0.0/../../../../riscv32-corev-elf/bin/ld: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /opt/corev/bin/../lib/gcc/riscv32-corev-elf/11.0.0/../../../../riscv32-corev-elf/bin/ld)

collect2: error: ld returned 1 exit status
```
@strichmo, I _believe_ this is all set-up properly, but your review would be welcome.  A particular item is that I needed to comment out all the `_stall` tests.

### CODE REVIEW

**Review by strichmo — CHANGES_REQUESTED** [review]
@MikeOpenHWGroup Please rip out the _stall tests completely from these YAMLs.  I should not have PRed these in the first place.  I have gone to a methodology in the interim where an entire regression will enable stalls or not.  Once the debug tests are stable we will just enable stalls on all simulations and let UVM distributions/constraints resolve.

**Comment by MikeOpenHWGroup** [comment]
Hi @aimeepsutton and @strichmo.  I've removed the "do not merge" label from this pull-request.  From my perspecitive it is good-to-go:
- updated Docker image with the latest dsim and the COREV and PULP toolchains
- increased timeout to 6 hours
- removed the stall testcases

**Review by aimeepsutton — APPROVED** [review]
Looks good to me Mike.

**Review by strichmo — APPROVED** [review]
Looks good to me.

**Pull request merged**
