### PR TITLE
Non-implemented CSR Check

### PR DESCRIPTION
**Pull request by emgens**
Added explicit check for non implemented CSR's to riscv_csr test.  
Cleaned up cv32e20_csr_template.yaml. 
This should run cleanly with cve2 pull request [167](https://github.com/openhwgroup/cve2/pull/167)
There is an entry to work around issue [179](https://github.com/openhwgroup/cve2/issues/179), this should be removed once this issue is cleared.

### CODE REVIEW

**Review by MikeOpenHWGroup — APPROVED** [review]
LGTM @emgens.  _Really_ appreciate the README!

Question: when I run `riscv_csr` locally with Questasim it fails with this error message:
```
# ERROR: Unexpected illegal instruction while accessing CSR 0xc00
```
I assume that this is related to #166, is that correct?

**Comment by emgens** [comment]
> LGTM @emgens. _Really_ appreciate the README!
> 
> Question: when I run `riscv_csr` locally with Questasim it fails with this error message:
> 
> ```
> # ERROR: Unexpected illegal instruction while accessing CSR 0xc00
> ```
> 
> I assume that this is related to #166, is that correct?

It's [#167](https://github.com/openhwgroup/cve2/pull/167), but yes.  That pull request implements the user space CSR's, so you'll get this error if that isn't included.

**Comment by emgens** [comment]
There are known failures in this test case that should be resolved by CVE2 pull request [#167](https://github.com/openhwgroup/cve2/pull/167)

**Comment by MikeOpenHWGroup** [comment]
Thanks @emgens.  I will merge this in and add the `riscv_csr` test to the CI regression when  [cve2 #167](https://github.com/openhwgroup/cve2/pull/167) is resolved.

**Pull request merged**
