### PR TITLE
Testbench updates according to updated IRQ interface

### PR DESCRIPTION
**Pull request by Silabs-ArjanB**
Testbench updates matching IRQ related changes from https://github.com/openhwgroup/core-v-docs/issues/50

The corresponding RTL pull requests are:

- https://github.com/openhwgroup/cv32e40p/pull/358
- https://github.com/openhwgroup/cv32e40p/pull/299

Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

### CODE REVIEW

**Comment by Silabs-ArjanB** [comment]
The above pull requests were merged already.

I now updated this branch with the latest from the core-v-verif master branch and I also made it work with the latest cv32e40p repos 8e22c994198ad08f4cacf239d56d98e1cc25627b

**Comment by MikeOpenHWGroup** [comment]
Hi @Silabs-ArjanB.  This PR is superseded by the latest merge onto the master branch.   The testbenches are now pointing at the (current) latest RTL (8e22c99).   I will retire this PR.

**Comment by Silabs-ArjanB** [comment]
Hi @MikeOpenHWGroup I do not agree with closing this one. This pull request has many required updates that are not present in the merge that was done. Specifically this contains the actual interrupt hookup and required updateds to mm_ram.

**Comment by MikeOpenHWGroup** [comment]
The "actual interrupt hookup and required updates to the mm_ram" are exactly what I do not want to merge in at this time.  These were done absent of an update to the verification strategy and without my buy-in.  Also, the changes to the step-and-compare make some assumptions about the ISS that may or may not be true (I have a meeting Monday morning with Imperas to discuss).

Nevertheless, this PR represents a lot of well intentioned work.  How about this:
1. Create another PR to merge in the changes to the tool control files.  I do not use those, but I am willing to bet they would be very useful to many others.
2. I will create a new branch `core-v-verif:ArjanB_irq`.
3. Create a new PR to merge from `Silabs-ArjanB:ArjanB_irq` to `core-v-verif:ArjanB_irq`.  I will accept that immediately and we can then discuss which of it should be merged into the master branch, pending discussions with Imperas, em-micro and yourself.

**Comment by Silabs-ArjanB** [comment]
Hi @MikeOpenHWGroup Good to see it was done intentionally. I will leave it like this then; you can merge in the parts according to your above plan when/if you want then.

**Pull request closed without merging**
