### PR TITLE
Adding riscv-arch-test suite to CVA6 core

### PR DESCRIPTION
**Pull request by spidugu444**

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@spidugu444   Can you add the modification done in #1612 to execute the CI job from .gitlab-ci/cva6.yaml ? Thanks

**Comment by spidugu444** [comment]
Hi @JeanRochCoulon, suggested changes has been added in gitlab branch and raised [merge request](https://gitlab.thalesdigital.io/riscv/core-v-verif/-/merge_requests/13) for the same.

**Comment by JeanRochCoulon** [comment]
Hello @spidugu444 
To merge your PR on GitHub, your modification need to appear on GitHub (not in GitLab). Please move your modification from GitLab to GitHub.
Regards

**Comment by fatimasaleem** [comment]
Hello @spidugu444 - I see in the PR you have added yaml files for two configurations, for `cv32a60x` which is running the tests (C, M and I) for this config which is fine as this configuration does not have the support for F, D, and B. But what about `cv64a6_imafdc_sv39`? Shouldn't we run all the tests on this configuration including [F](https://github.com/riscv-non-isa/riscv-arch-test/tree/main/riscv-test-suite/rv64i_m/F/src), [D](https://github.com/riscv-non-isa/riscv-arch-test/tree/main/riscv-test-suite/rv64i_m/D/src) and [privilege](https://github.com/riscv-non-isa/riscv-arch-test/tree/main/riscv-test-suite/rv64i_m/privilege/src) tests? 

Also, I think It will be good if we could add one more file for `cv32a6_imafc_sv32` config.

**Comment by JeanRochCoulon** [comment]
Thank you @fatimasaleem to raise the point. As this PR focuses on step1 verification, this is out of scope. But I would encourage you to submit a GitHub issue to log the point. This should be address in another PR.

**Pull request merged**
