### PR TITLE
Port .metrics.json into individual regression YAMLs - use dynamic metrics json generation

### PR DESCRIPTION
**Pull request by strichmo**
Signed-off-by: Steve Richmond <Steve.Richmond@silabs.com>

### CODE REVIEW

**Comment by strichmo** [comment]
All metrics regressions passed on my fork.

https://openhwgroup.metrics.ca/steve.richmond.silabs-strichmo.fork0/results/regressionRuns

**Comment by strichmo** [comment]
@MikeOpenHWGroup I was so excited to get this out the door I completely forgot that I neglected to port ci_check as well.  That script will need to use the YAMLs.  Should not be a big deal to port.  I'll get to this in the morning.

**Please don't merge yet into master, but feel free to inspect and/or test on your own.**

**Review by MikeOpenHWGroup — COMMENTED** [review]
Wow, breath-taking stuff @strichmo.  The changes are significant and entail a certain amount of trust - I need to see it all in action to fully get my head around it.  So I will merge this all onto a private branch and kick the tires a bit before doing a merge.

**Comment by strichmo** [comment]
ci_check is now ported to work off of the YAML as well.  This is should be a complete, proper pull request now!

**Review by MikeOpenHWGroup — APPROVED** [review]
Looks good @strichmo.  There is a small issue with `cv32/regress/cv32_full.yaml` that affects the debug_test.  I'll push in a fix for that separately.

**Pull request merged**
