### PR TITLE
Silabs robin/pr/master merge 220118

### PR DESCRIPTION
**Pull request by silabs-robin**
Here is the merge of {`cv32e40p/release`, `cv32e40x/release`, `cv32e40s/release`, 40x->40s manual merge} into `master`.

It does not pass all `rel_check`s yet.
40x passes, but sporadically don't
40s had 2 failures in the last run (`cv32e40s_csr_access_test`, `cv32e40s_readonly_csr_access_test`).
40p has (consistently) 2 failures (`corev_rand_debug_single_step` twice).
The 40x/40s failures are ok as these are both WIP.
The 40p I would like to request some help with debugging.

Before merge, we should fix the 40p failures, review the 40x->40s manual merge, review that we accept the current 40x/40s failures, and review the overall diff/commitlog of the whole merge.
@MikeOpenHWGroup @silabs-hfegran @silabs-mateilga 

If it helps review, use github's compare feature on the step-wise [branches](https://github.com/silabs-robin/core-v-verif/branches/all) I used for this.
That is, branch `silabs-robin/pr/master_merge_220118`, `.../master_merge_220118_40p`, ..., `.../master_merge_220118_40p_40x_40s_x2s`.
For example, [here](https://github.com/silabs-robin/core-v-verif/compare/silabs-robin/pr/master_merge_220118_40p_40x_40s...silabs-robin:silabs-robin/pr/master_merge_220118) is the diff of my manual 40x->40s merging.

### CODE REVIEW

**Review by MikeOpenHWGroup — APPROVED** [review]
Thanks for this @silabs-robin.  Approving based on:
1. A quick review of the files that were changed to convince myself I'd seen it all before.
2. Local integration level regressions (not full regressions) under both dsim and xrun for the e40p, e40x and e40s.

**Comment by silabs-robin** [comment]
Changing PR status: "draft"->"ready for review".
The 40P issue can still be a reason to wait, but I am unblocking this PR so we can move on when we are ready.

**Comment by silabs-hfegran** [comment]
@MikeOpenHWGroup - What is the status on the regression error for the 40p? Should we proceed with this merge before that is resolved?

**Comment by MikeOpenHWGroup** [comment]
I've determined that it is an environment, not DUT error and suspect that it is caused by the introducing of an updated toolchain.  In my opinion it is not  worth gating this merge for that as it will not impede the 40pv2 and I can resolve it on the master branch.

**Comment by silabs-robin** [comment]
Ok. Then it should be ready to merge. I'll start the "master_to_rel" after this is in.

**Pull request merged**
