### PR TITLE
ISACOV : Add csr directed tests

### PR DESCRIPTION
**Pull request by AyoubJalali**

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Can we roll all these into a single test?

**Comment by AyoubJalali** [comment]
> Can we roll all these into a single test?

I think we can, but I prefer it like that, every test related to a CSR instruction (CSRRW, CSRRS,C ...)

**Comment by MikeOpenHWGroup** [comment]
> > Can we roll all these into a single test?

> I think we can, but I prefer it like that, every test related to a CSR instruction (CSRRW, CSRRS,C ...)

In general I do as well.  However, we are moving towards a time when we will have very large regressions of many hundreds of tests.  The overhead of multiple trivial tests will start to be significant.  At this point the stability of the CVA6 is such that we expect these CSR instruction tests to always pass, so the value of many trivial tests is now less than the cost of running may trivial tests in regression.

I strongly recommend merging these into a single test-program.

**Comment by AyoubJalali** [comment]
@MikeOpenHWGroup could you check this please, I merge all the tests in one.

**Review by MikeOpenHWGroup — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
Good work @AyoubJalali, thanks!

**Pull request merged**
