### PR TITLE
Updated filename for new agent script

### PR DESCRIPTION
**Pull request by datum-dpoulin**
Updated filename for new agent script in common makefile to match changes in v1p1

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
This looks good @datum-dpoulin, thanks for keeping this updated.

Before merging, I have a favour to ask.  When this PR is merged, it will kick-off three large-ish regressions, one each for CV32E40P, E40X and E40S.  This is unnecessary for this PR, so it would be good to avoid wasting cycles on the CI platform.  Can you update your PR commit message to add `[skip actions]`?  See [this](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) for additional details.

Thanks!

**Comment by datum-dpoulin** [comment]
Done

**Comment by silabs-hfegran** [comment]
@MikeOpenHWGroup Can this be merged now?

**Review by MikeOpenHWGroup — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
Hmm.  I cannot see that the commit message was changed, but maybe I am not sure where to look.   In the interests of getting this closed, I will merge it.

**Pull request merged**
