### PR TITLE
Fv - Update Flist

### PR DESCRIPTION
**Pull request by silabs-robin**
Just the periodic sync of the formal flist.

We still have this https://github.com/openhwgroup/core-v-verif/issues/1384 ticket to properly fix it.
But I don't know how to optimally solve it...

### CODE REVIEW

**Comment by silabs-robin** [comment]
@MikeOpenHWGroup, you previously said: _"I would like to have one-and-only-one manifest (flist)"_

* Current flists:
    1. The main 40s flist: https://github.com/openhwgroup/core-v-verif/blob/cv32e40s/dev/cv32e40s/tb/uvmt/uvmt_cv32e40s.flist
    2. Two Imperas flists: (right next to the main 40s flist)
    3. And, one special formal flist: (ref this PR) (duplicates a subset of the main 40s flist)

Problem:
Formal cannot handle all the UVM stuff from the main 40s flist.

Proposal:
Take whatever is common between "the main 40s flist" and the "special formal flist" and separate it out into one (or more) common flist(s).
_(One alternative is to dedicating an effort to creating a dummy uvm library, hope that that will solve it, and suffer unnecessarily long compilation times as non-used files are compiled.)_

**Comment by MikeOpenHWGroup** [comment]
> I would like to have one-and-only-one manifest (flist)

True, I said that.  But I wasn't entirely clear.  The "one manifest" refered to the RTL.  Currently we have a manifest for RTL simulation and another for synthesis.  Bad.  I would dearly love to fix that and suggest that using FuseSoC could be a solution.

As for the verification environment, we can have heirarchical netlist.

**Comment by silabs-robin** [comment]
@MikeOpenHWGroup, I moved the part from `uvmt_cv32e40s.flist` called `// CV32E40S test bench files` into a new file called `uvmt_cv32e40s_tb_files.flist`.

Now that new flist is used by formal too, so that it doesn't need to maintain its own copy of those lines, since it kept getting out of sync all the time and breaking the formal setup.

**Review by silabs-hfegran — APPROVED** [review]
Looks good to me

**Review by MikeOpenHWGroup — APPROVED** [review]

**Pull request merged**
