### PR TITLE
Added tests for PMP

### PR DESCRIPTION
**Pull request by silabs-kun**
Signed-off-by: Kun Zhu <Kun.Zhu@silabs.com>

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @silabs-hfegran, what is the status of this PR?

**Comment by silabs-robin** [comment]
Hi @MikeOpenHWGroup.

This PR is a continuation and cleanup of https://github.com/openhwgroup/core-v-verif/pull/1351 (we just closed that old PR).

There is 1 known problem with the very last of the tests that were written and we didn't debug it to its root cause yet.
My plan was to finish writing some PMP assertions and then get these PMP directed tests ready for merge (but the PMP assertions are dragging out).
All the other tests in this PR is something we had a code walkthrough and review meeting for, so we'd like to get it all merged after that one known problem is figured out.

**Comment by MikeOpenHWGroup** [comment]
> All the other tests in this PR is something we had a code walkthrough and review meeting for, so we'd like to get it all merged after that one known problem is figured out.

Works for me.  I'll put a "do not merge" label on this for now.  Please remove it when you feel it is ready for a merge. Also, GitHub is reporting a conflict and that will need to be resolved.

**Comment by MikeOpenHWGroup** [comment]
Hello @silabs-kun, @silabs-robin indicated that PR #1412 replaces this one.   If that is the case, please close this PR.  Thanks.

**Pull request merged**
