### PR TITLE
Define RVFI as CVA6 input parameter

### PR DESCRIPTION
**Pull request by JeanRochCoulon**
Signed-off-by: Jean-Roch Coulon <jean-roch.coulon@thalesgroup.com>

### CODE REVIEW

**Review by MikeOpenHWGroup — APPROVED** [review]
LGTM.  I will defer to @ASintzoff to execute the merge.

**Comment by MikeOpenHWGroup** [comment]
The github-actions is reporting a failure because the `FPGA Linux64 Boot` test failed.  However, GitHub is reporting that **All checks have passed**.  Is this a bug in the github-action, or do we allow merges if the FPGA linux boot test passes?

**Comment by JeanRochCoulon** [comment]
Indeed, the linux boot does not pass on FPGA. It seems to be a real bug, to be investigated.   :-(

**Comment by ASintzoff** [comment]
Included in #2019

**Pull request closed without merging**
